#### 1. Import Numpy

In [1]:
import numpy as np

#### 2. Array in Numpy

In [9]:
# 2.1 Scalar Array
a = np.array(10)
print(a)

# 2.2 Vector Array
row = np.array([1, 2, 3]) # 1 row and 3 columns
col = np.array([[1], [2], [3]]) # 3 rows and 1 column
print(row)
print(col)

# 2.3 Matrix Array
matrix = np.array([[10, 11, 12], [13, 14, 15]]) # 2x3 matrix
print(matrix)

10
[1 2 3]
[[1]
 [2]
 [3]]
[[10 11 12]
 [13 14 15]]


#### 3. การหาค่าทางสถิติของข้อมูลด้วย numpy

In [19]:
stat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # 3x4 matrix
print(stat)

# หาค่าสูงสุด (max)
print("Max:", np.max(stat))

# หาค่าต่ำสุด (min)
print("Min:", np.min(stat))

# หาค่าเฉลี่ย (mean)
print("Mean:", np.mean(stat))

# ค่ามัธยฐาน (median)
print("Median:", np.median(stat))

# ค่าส่วนเบี่ยงเบนมาตรฐาน (standard deviation)
print("Standard deviation:", np.std(stat))

# ค่าความแปรปรวน (variance)
print("Variance:", np.var(stat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max: 12
Min: 1
Mean: 6.5
Median: 6.5
Standard deviation: 3.452052529534663
Variance: 11.916666666666666
